### ISSUE TITLE
Show Portfolio

### ISSUE THREAD

**Issue by JDSustar** [mleone10/marioleone.me#1]
I don't see your Show portfolio on your website. This is a severe oversight and a High Priority issue. Please resolve ASAP.

Website is literately unplayable right now.

**Comment by mleone10** [comment]
Thank you for your interest in marioleone.me.  We've considered your feature request, but have ultimately decided that it does not fit with the intent of the site at this time.  Please note that we still might consider your proposal at a later date.

Once again, thank you for your suggestion.

Best,
- Mario
